
#Heming's aliases:
alias rangoon='cd /workspace/RANGOON_GA/src/ '
alias panama='cd /workspace/PANAMA_dev/src/ '
alias desktop='cd ~/Desktop '
alias qq='cd /media/Tools/linuxqq_v1.0.2-beta1_i386 ;  qq & ; '
alias mytomcat='cd /media/Tools/apache-tomcat-6.0.33/bin ' 

alias codeperl='cd /media/Coding/Perl '
alias codeand='cd /media/Coding/And/Tips_Doc '
alias andsrc='cd /media/Coding/And/AnSrc_froyo '
alias andemu='emulator -avd 2.2_noinstall -partition-size 100 & '

alias pushgithub='cd /media/Coding/And/SpalSvr;git push github master; cd /media/Coding/And/SpalClient;git push github master; cd /media/Coding/And/SpalClientDaemon; git push github master;'
alias pullgithub='cd /media/Coding/And/SpalSvr;git pull github master; cd /media/Coding/And/SpalClient;git pull github master; cd /media/Coding/And/SpalClientDaemon; git pull github master;'

alias startmi='/workspace/startmi.sh'
alias stopmi='/workspace/stopmi.sh'
alias statusmi='/workspace/statusmi.sh'
alias statusdc='sudo service dc status '
alias startdc='sudo service dc restart '
alias buildbod='/workspace/buildbod.sh'
alias buildmi='/workspace/buildmi.sh'
alias buildmsc='/workspace/buildmsc.sh'

alias svim='sudo vim '
alias yum='sudo yum '
alias yumlist='sudo yum list |grep -i '
alias yuminstall='sudo yum install '
alias classver='java -cp /media/Tools/JavaParser JavaParser '
#alias goagent='python26 /media/Tools/goagent/current/local/proxy.py '
alias goagent='python2.7 /media/Tools/goagent/current/local/proxy.py '

#common aliases
alias cls='clear'
alias ip4='ip -4 addr '
alias ping='ping -c 5 '
alias antp='ant -p '
alias s='ssh -l root '
alias llart='ls -lart --color=tty'
alias lla='ls -la --color=tty'
alias psa1='sudo ps -aux |grep -i '
alias port1='sudo netstat -tuapn |grep -i '

alias psa='ps -aux |grep -i '
alias port='netstat -tuapn |grep -i '

alias qprestart='service qp_procmgr restart'
alias reqp='service qp_procmgr restart'
alias startqp='service qp_procmgr start '
alias stopqp='service qp_procmgr stop '
alias qpstatus='service qp_procmgr status '
alias recomcol='service comcol restart'

alias copyvmjars='~/vmcopy.sh'
alias copytovm='/workspace/copytovm.sh'
alias clearqp='ha.cleanup QP '
alias newbash='vim ~/.bashrc '
alias runbash='source ~/.bashrc '
alias killps='kill -9 '
alias komo='/media/Tools/Komodo-Edit-7/lib/mozilla/komodo '
alias komo='/media/Tools/Komodo-Edit-8/bin/komodo '
alias unlockkomo='rm /home/users/she/.komodoedit/8.0/running.lock; rm /home/users/she/.komodoedit/8.0/XRE/.parentlock '

alias sqllogin='mysql -A -uroot -proot camiant -A '
alias cmts='cd /opt/camiant/bin/'
alias runjcmts='/opt/camiant/bin/jcmts -c -p '
alias rcmgr='/opt/camiant/rc/bin/rcmgr '
alias bodmgr='/opt/camiant/bod/bin/bodmgr '
alias cdlog='cd /var/camiant/log/'
alias tailrc='cd /var/camiant/log/ ; tail -100f rc.log'
alias vimrclog='cd /var/camiant/log/ ; vim -100f rc.log'
alias cdwebapps='cd /opt/camiant/tomcat/webapps/'
alias cdbdb='cd /var/camiant/db/home '
alias lswebapps='ls -lart /opt/camiant/tomcat/webapps/ --color=tty '
alias cdplat='cd /opt/camiant/platform/'
alias cdrc='cd /opt/camiant/rc/'

alias vimlog='vim /etc/camiant/logconfig/ '
alias vimhost='vim /home/users/she/.ssh/known_hosts '
alias jd='/media/Tools/jd-gui &'
alias dex2jar='/home/users/she/bin/dex-translator-0.0.9.3/dex2jar.sh '
alias fullpath='ls | sed "s:^:`pwd`/:"'
alias lspath='find $PWD |grep '
alias mipages='cd /opt/camiant/tomcat/webapps/mi/pages '
alias runseagull='cd ~/rangoon/script; ./runseagull.py  -f ../environment/localhost.cfg '
alias usejdk6='export JAVA_HOME=/media/Tools/jdk1.6.0_37_x64; export PATH=$JAVA_HOME/bin:$PATH'
alias useant19='export ANT_HOME=/media/Tools/ant/apache-ant-1.9.0; export PATH=$ANT_HOME/bin:$PATH '

alias acc='$ACCUREV_HOME/bin/accurev '
alias aclogin='$ACCUREV_HOME/bin/accurev login she she '
alias acupdate='$ACCUREV_HOME/bin/accurev update '
alias acgui='$ACCUREV_HOME/bin/acgui &'
alias updatecode='aclogin; acupdate; '

alias nbod='cd /workspace/FG_merge_she/src/nbod/java '
alias ncommon='cd /workspace/FG_merge_she/src/common/java '
alias buildrc='fargo_merge; ant stageall && copytovm slave '
alias buildrc1='fargo_merge; ant stageall && copytovm mpe '
alias buildrc2='fargo_merge; ant stageall && copytovm mpe '
alias buildbod='cd /workspace/FG_merge_she/src/nbod/java; ant stageall && copytovm bod '

#alias fargo='cd /media/workspace/FARGO_dev/src/msc/java '
alias fargo_merge='cd /media/workspace/FG_merge_she/src/msc/java '

#alias cdsrc='cd /workspace/RANGOON_dev/src/'
#alias cd..='cd ..'
        
alias starttomcat='sudo service tomcat restart'
alias stoptomcat='sudo service tomcat restart'

#alias vmhk='s -X 10.60.24.180 ' 
#alias vmcmp='s -X 10.60.24.189 ' 
#alias vmmpe='s -X 10.60.24.191 ' 
#alias vmbod='s -X 10.60.24.205 '
alias vmslave1='s -X 10.60.57.75 '
alias vmslave2='s -X 10.60.57.77 '
#alias vmslave1='s -X 10.60.27.107 '
#alias vmslave2='s -X 10.60.27.109 '

alias nvmcmp='s -X 10.60.32.211 '
alias nvmmpe='s -X 10.60.32.213 ' 
alias nvmbod='s -X 10.60.32.217 '
alias nvmma='s -X 10.60.32.219 '
alias nvmslave1='s -X 10.60.57.75 '
alias nvmslave2='s -X 10.60.57.77 '

#alias vmperf='s -X 10.60.28.73 '
#alias vmperfcmp='s -X 10.60.28.71 '
#alias vmperf1='s -X 10.60.28.215 '
#alias vmperfcmp1='s -X 10.60.28.105 '
alias vmseagull='s -X 10.60.27.190 '

alias virtcmp='s -X 10.60.24.247 '

