
package studentpal.ws.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PhoneConnectorWsService", targetNamespace = "urn:cn.com.studentpal:PhoneConnectorWs", wsdlLocation = "http://localhost:8080/StudentPal/PhoneConnector?wsdl")
public class PhoneConnectorWsService
    extends Service
{

    private final static URL PHONECONNECTORWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(studentpal.ws.wsclient.PhoneConnectorWsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = studentpal.ws.wsclient.PhoneConnectorWsService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/StudentPal/PhoneConnector?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/StudentPal/PhoneConnector?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PHONECONNECTORWSSERVICE_WSDL_LOCATION = url;
    }

    public PhoneConnectorWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneConnectorWsService() {
        super(PHONECONNECTORWSSERVICE_WSDL_LOCATION, new QName("urn:cn.com.studentpal:PhoneConnectorWs", "PhoneConnectorWsService"));
    }

    /**
     * 
     * @return
     *     returns PhoneConnectorWs
     */
    @WebEndpoint(name = "PhoneConnectorWsPort")
    public PhoneConnectorWs getPhoneConnectorWsPort() {
        return super.getPort(new QName("urn:cn.com.studentpal:PhoneConnectorWs", "PhoneConnectorWsPort"), PhoneConnectorWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneConnectorWs
     */
    @WebEndpoint(name = "PhoneConnectorWsPort")
    public PhoneConnectorWs getPhoneConnectorWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cn.com.studentpal:PhoneConnectorWs", "PhoneConnectorWsPort"), PhoneConnectorWs.class, features);
    }

}
